### ISSUE TITLE
FR: registry URL as output

### ISSUE THREAD

**Issue by pataquets** [GoogleCloudPlatform/terraform-google-artifact-registry#19]
I'm using the module to deploy a Docker image on Cloud Run.
It would be very convenient to have the repo URL `europe-west1-docker.pkg.dev/your-project/your-repo/image` available as an output for referencing from other locations (in this case, the CR deployed image).

**Comment by pataquets** [comment]
@prabhu34 any feedback on this? It would definitely improve module's usability.

**Comment by prabhu34** [comment]
> @prabhu34 any feedback on this? It would definitely improve module's usability.

There is no output that Terraform knows to get this URL directly. The API doesn't support either. 
I would recommend to form this URL in the module invocations, based on the GAR ID that is already available as an output, location and name.

Closing this FR.

**Comment by pataquets** [comment]
@prabhu34 "API doesn't support" means Google Cloud's API or upstream Terraform provider?
If the latter, since it's not such a wildly unreasonable feature to expect, I guess it would be better to keep this open until upstream/base Terraform provider implements the output.
Additionally, this would be a legitimate FR for the upstream Terraform provider, which would be a dependency for this issue.

**Comment by pataquets** [comment]
> @prabhu34 "API doesn't support" means Google Cloud's API or upstream Terraform provider? If the latter, since it's not such a wildly unreasonable feature to expect, I guess it would be better to keep this open until upstream/base Terraform provider implements the output. Additionally, this would be a legitimate FR for the upstream Terraform provider, which would be a dependency for this issue.

@prabhu34 ping?

**Comment by pataquets** [comment]
Cross-linking to upstream provider issue: hashicorp/terraform-provider-google#11355
